SPRITE_SIZE = 16
HALF_SPRITE_SIZE = SPRITE_SIZE / 2
QUARTER_SPRITE_SIZE = HALF_SPRITE_SIZE / 2
GAME_HEIGHT = 90
GAME_WIDTH = 160
MIN_X = 0
MAX_X = GAME_WIDTH - SPRITE_SIZE
MID_X = MIN_X + (MAX_X - MIN_X) / 2
MIN_Y = 16
MAX_Y = GAME_HEIGHT - SPRITE_SIZE
MID_Y = MIN_Y + (MAX_Y - MIN_Y) / 2

SCENE_INTRO = 0
SCENE_IN_GAME = 1
SCENE_GAME_OVER = 2
SCENE_WIN = 3

TYPE_PLAYER = 0
TYPE_ENEMY = 1
TYPE_BULLET = 2

PLAYER_SPEED = 30
PLAYER_RELOAD_TIME = 0.5

ENEMY_SPEED = 20
ENEMY_RELOAD_TIME = 1.3
ENEMY_RUN_FROM_PLAYER_DISTANCE = 50
ENEMY_MIN_MOVE_TIME = 0.5 -- max move time is this plus 1 second

BULLET_SPEED = PLAYER_SPEED * 2
BULLET_LIFETIME = 2.5

CHAR_WIDTH = 6
CHAR_HEIGHT = 10

SFX_EXPLOSION = "explosion"
SFX_HIT = "hit"
SFX_SHOOT = "shoot"
SFX_WAVE_START = "wave_start"
SFX_BEEP = "beep"
SFX_WIN = "win"